### ISSUE TITLE
MoviePy error

### ISSUE THREAD

**Issue by vinswat** [nathan-149/automated_youtube_channel#15]
Hi, 

The script works up until it tries to compile the video, I have intsalled FFMPEG but it didn't make any difference - Anyone else getting this ? 
''  
Moviepy - Building video ./JUNE_2021_v15.mp4.
MoviePy - Writing audio in /tmp/temoaudiofile.m4a
chunk:   0%|                                                              | 2/5574 [00:01<1:06:47,  1.39it/s, now=None]Routine Failed on OS error: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file /tmp/temoaudiofile.m4a:

b'/tmp/temoaudiofile.m4a: No such file or directory\r\n'

In case it helps, make sure you are using a recent version of FFMPEG (the versions in the Ubuntu/Debian repos are deprecated).  ''

**Comment by vinswat** [comment]
I see this was previously closed, solved by changing the path (done) and creating a file with the same name as the one missing. I assume he meant temoaudiofile.m4a

**Comment by Abhidcruez** [comment]
Can help me out I have the same problem but not able to solve it
