### ISSUE TITLE
help! got stuck after authorization

### ISSUE THREAD

**Issue by tikuranbessa** [nathan-149/automated_youtube_channel#5]
it doesn't start scarping videos after i submit the authorization code. what do i have to do? did i miss something?
![Capture](https://user-images.githubusercontent.com/82719092/115118408-004b7c80-9f71-11eb-8dad-3b7b1bd773c2.PNG)

**Comment by arcasull2020** [comment]
I've got this issue too please help!

**Comment by tikuranbessa** [comment]
> I've got this issue too please help!

Apparently this one worked for me, maybe got some update or some thing. check it out.

https://github.com/KumarK22/automated_youtube_channel
